<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Authors>Pragya Himanshu</Authors>
        <Company>Pragya Himanshu</Company>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Http" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Analyzers" />
        <PackageReference Include="Microsoft.AspNetCore.RateLimiting" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Application\Application.csproj" />
    </ItemGroup>
</Project>
